function HerbsInformation(){
    const trees = [
        ["Oak", "Quercus robur", "Temperate", "Leaves, Bark", "Oak is used for its strong timber and has various medicinal uses for skin conditions."],
        ["Maple", "Acer saccharum", "Temperate", "Sap, Leaves", "Maple syrup is made from its sap, and its leaves have anti-inflammatory properties."],
        ["Pine", "Pinus sylvestris", "Temperate", "Needles, Resin", "Pine needles are used for respiratory issues and the resin for wounds."],
        ["Cherry", "Prunus avium", "Temperate", "Fruit, Bark", "Cherry bark has been used for coughs and the fruit is rich in antioxidants."],
        ["Apple", "Malus domestica", "Temperate", "Fruit, Leaves", "Apples are used for their antioxidant properties and as a source of vitamins."],
        ["Cedar", "Cedrus libani", "Temperate", "Wood, Resin", "Cedar wood is used for its durability and the resin for medicinal purposes."],
        ["Birch", "Betula pendula", "Temperate", "Bark, Leaves", "Birch bark is used for its anti-inflammatory properties and the leaves for urinary tract health."],
        ["Walnut", "Juglans regia", "Temperate", "Nuts, Leaves", "Walnut nuts are rich in omega-3s and the leaves have antimicrobial properties."],
        ["Willow", "Salix alba", "Temperate", "Bark", "Willow bark is known for its pain-relieving properties and is used as an anti-inflammatory."],
        ["Eucalyptus", "Eucalyptus globulus", "Tropical", "Leaves", "Eucalyptus leaves are used for respiratory issues and have antiseptic properties."],
        ["Mango", "Mangifera indica", "Tropical", "Fruit, Leaves", "Mangoes are rich in vitamins and the leaves are used in traditional medicine for diabetes."],
        ["Papaya", "Carica papaya", "Tropical", "Fruit, Leaves", "Papaya is used for digestion and its leaves have anti-inflammatory effects."],
        ["Fig", "Ficus carica", "Mediterranean", "Fruit, Leaves", "Fig fruit is used for digestive health and leaves for their anti-inflammatory properties."],
        ["Pomegranate", "Punica granatum", "Mediterranean", "Fruit, Peel", "Pomegranate is known for its antioxidant properties and the peel is used for digestive health."],
        ["Olive", "Olea europaea", "Mediterranean", "Fruit, Leaves", "Olive oil is used for heart health, and leaves have anti-inflammatory properties."],
        ["Avocado", "Persea americana", "Tropical", "Fruit", "Avocado is rich in healthy fats and used for skin health."],
        ["Coconut", "Cocos nucifera", "Tropical", "Fruit, Oil", "Coconut is used for its oil and has various health benefits including hydration and digestion."],
        ["Neem", "Azadirachta indica", "Tropical", "Leaves, Bark", "Neem has antibacterial properties and is used in treating skin conditions."],
        ["Tulsi", "Ocimum sanctum", "Tropical", "Leaves", "Tulsi is known for its immune-boosting and anti-inflammatory properties."],
        ["Aloe Vera", "Aloe barbadensis", "Tropical", "Gel, Leaves", "Aloe Vera is used for its skin-soothing and healing properties."],
        ["Ginger", "Zingiber officinale", "Tropical", "Root", "Ginger helps in digestion and has anti-nausea effects."],
        ["Turmeric", "Curcuma longa", "Tropical", "Root", "Turmeric is known for its anti-inflammatory and antioxidant properties."],
        ["Peppermint", "Mentha piperita", "Temperate", "Leaves", "Peppermint is used for relieving digestive issues and headaches."],
        ["Lavender", "Lavandula angustifolia", "Temperate", "Flowers", "Lavender is used for its calming and stress-relieving properties."],
        ["Rosemary", "Rosmarinus officinalis", "Mediterranean", "Leaves", "Rosemary is used for improving memory and relieving muscle pain."],
        ["Thyme", "Thymus vulgaris", "Mediterranean", "Leaves", "Thyme has antibacterial properties and is used to treat coughs and colds."],
        ["Chamomile", "Matricaria chamomilla", "Temperate", "Flowers", "Chamomile is known for its calming effects and helps with insomnia."],
        ["Echinacea", "Echinacea purpurea", "Temperate", "Leaves, Flowers", "Echinacea is used to boost the immune system and treat infections."],
        ["Ginseng", "Panax ginseng", "Temperate", "Root", "Ginseng helps in boosting energy and reducing stress."],
        ["Dandelion", "Taraxacum officinale", "Temperate", "Leaves, Root", "Dandelion is used for liver detoxification and as a diuretic."],
        ["Licorice", "Glycyrrhiza glabra", "Temperate", "Root", "Licorice root is used for soothing digestive issues and sore throats."],
        ["Fennel", "Foeniculum vulgare", "Mediterranean", "Seeds, Bulb", "Fennel seeds are used to aid digestion and reduce bloating."],
        ["Cardamom", "Elettaria cardamomum", "Tropical", "Seeds", "Cardamom is used for digestive issues and has antimicrobial properties."],
        ["Cilantro", "Coriandrum sativum", "Mediterranean", "Leaves, Seeds", "Cilantro is known for its detoxifying and digestive health benefits."],
        ["Oregano", "Origanum vulgare", "Mediterranean", "Leaves", "Oregano is used for its antioxidant properties and to treat respiratory conditions."],
        ["Basil", "Ocimum basilicum", "Tropical", "Leaves", "Basil is used for its anti-inflammatory and antioxidant benefits."],
        ["Marigold", "Calendula officinalis", "Temperate", "Flowers", "Marigold is used to treat wounds and as an anti-inflammatory agent."],
        ["Jasmine", "Jasminum officinale", "Temperate", "Flowers", "Jasmine is used for its calming properties and to treat skin conditions."],
        ["Hibiscus", "Hibiscus rosa-sinensis", "Tropical", "Flowers", "Hibiscus is known for its antioxidant properties and is used to lower blood pressure."],
        ["Passionflower", "Passiflora incarnata", "Tropical", "Flowers, Leaves", "Passionflower is used for its calming effects and to treat anxiety."],
        ["Saw Palmetto", "Serenoa repens", "Tropical", "Berries", "Saw Palmetto is used to treat symptoms of benign prostatic hyperplasia."],
        ["Ginger", "Zingiber officinale", "Tropical", "Root", "Ginger aids digestion and is used to treat nausea and inflammation."],
        ["Holy Basil", "Ocimum tenuiflorum", "Tropical", "Leaves", "Holy Basil is used for its stress-relieving and immune-boosting properties."],
        ["Schisandra", "Schisandra chinensis", "Temperate", "Berries", "Schisandra is used for its adaptogenic properties and liver health."],
        ["Rhodiola", "Rhodiola rosea", "Temperate", "Root", "Rhodiola is known for its stress-reducing and fatigue-fighting properties."],
        ["Hawthorn", "Crataegus monogyna", "Temperate", "Berries, Leaves", "Hawthorn is used for cardiovascular health and to improve blood flow."],
        ["Lemon Balm", "Melissa officinalis", "Temperate", "Leaves", "Lemon Balm is used for its calming effects and to alleviate digestive issues."],
        ["Yarrow", "Achillea millefolium", "Temperate", "Leaves, Flowers", "Yarrow is used for its anti-inflammatory and wound-healing properties."],
        ["St. John’s Wort", "Hypericum perforatum", "Temperate", "Leaves, Flowers", "St. John’s Wort is used to treat depression and anxiety."],
        ["Mullein", "Verbascum thapsus", "Temperate", "Leaves, Flowers", "Mullein is used for respiratory health and to soothe coughs."],
        ["Marshmallow", "Althaea officinalis", "Temperate", "Root, Leaves", "Marshmallow is used to soothe mucous membranes and treat coughs."],
        ["Elderberry", "Sambucus nigra", "Temperate", "Berries, Flowers", "Elderberry is used for its immune-boosting and antiviral properties."],
        ["Goldenrod", "Solidago canadensis", "Temperate", "Flowers", "Goldenrod is used to treat urinary tract infections and inflammation."],
        ["Bee Balm", "Monarda didyma", "Temperate", "Leaves, Flowers", "Bee Balm is used for its antibacterial properties and to relieve stress."],
    ]
    

    return trees;
}

export default HerbsInformation;